apiVersion: v1
kind: ServiceAccount
metadata:
  name: warden-api
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: warden-api-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "delete", "get", "list", "watch"]
  - apiGroups: ["cilium.io"]
    resources: ["ciliumnetworkpolicies"]
    verbs: ["create", "delete", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: warden-api-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: warden-api
    namespace: default
roleRef:
  kind: Role
  name: warden-api-role
  apiGroup: rbac.authorization.k8s.io